/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RayzorverseRouteImport } from './routes/rayzorverse'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAchievementsRouteImport } from './routes/admin/achievements'
import { Route as AdminCapabilitiesRouteImport } from './routes/admin/capabilities'
import { Route as AdminCollaborationsRouteImport } from './routes/admin/collaborations'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as AdminLeadershipRouteImport } from './routes/admin/leadership'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStoryRouteImport } from './routes/admin/story'
import { Route as AdminVenturesRouteImport } from './routes/admin/ventures'
import { Route as AdminWorkRouteImport } from './routes/admin/work'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RayzorverseRoute = RayzorverseRouteImport.update({
  id: '/rayzorverse',
  path: '/rayzorverse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/admin/achievements',
  path: '/admin/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCapabilitiesRoute = AdminCapabilitiesRouteImport.update({
  id: '/admin/capabilities',
  path: '/admin/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaborationsRoute = AdminCollaborationsRouteImport.update({
  id: '/admin/collaborations',
  path: '/admin/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/admin/experience',
  path: '/admin/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadershipRoute = AdminLeadershipRouteImport.update({
  id: '/admin/leadership',
  path: '/admin/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoryRoute = AdminStoryRouteImport.update({
  id: '/admin/story',
  path: '/admin/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenturesRoute = AdminVenturesRouteImport.update({
  id: '/admin/ventures',
  path: '/admin/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkRoute = AdminWorkRouteImport.update({
  id: '/admin/work',
  path: '/admin/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/rayzorverse': typeof RayzorverseRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/story': typeof AdminStoryRoute
  '/admin/ventures': typeof AdminVenturesRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/rayzorverse': typeof RayzorverseRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/story': typeof AdminStoryRoute
  '/admin/ventures': typeof AdminVenturesRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin': typeof AdminIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/rayzorverse': typeof RayzorverseRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/collaborations': typeof AdminCollaborationsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/leadership': typeof AdminLeadershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/story': typeof AdminStoryRoute
  '/admin/ventures': typeof AdminVenturesRoute
  '/admin/work': typeof AdminWorkRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/library'
    | '/rayzorverse'
    | '/admin/achievements'
    | '/admin/capabilities'
    | '/admin/collaborations'
    | '/admin/experience'
    | '/admin/leadership'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/story'
    | '/admin/ventures'
    | '/admin/work'
    | '/work/$slug'
    | '/admin/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/library'
    | '/rayzorverse'
    | '/admin/achievements'
    | '/admin/capabilities'
    | '/admin/collaborations'
    | '/admin/experience'
    | '/admin/leadership'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/story'
    | '/admin/ventures'
    | '/admin/work'
    | '/work/$slug'
    | '/admin'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/library'
    | '/rayzorverse'
    | '/admin/achievements'
    | '/admin/capabilities'
    | '/admin/collaborations'
    | '/admin/experience'
    | '/admin/leadership'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/story'
    | '/admin/ventures'
    | '/admin/work'
    | '/work/$slug'
    | '/admin/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LibraryRoute: typeof LibraryRoute
  RayzorverseRoute: typeof RayzorverseRoute
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminCapabilitiesRoute: typeof AdminCapabilitiesRoute
  AdminCollaborationsRoute: typeof AdminCollaborationsRoute
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminLeadershipRoute: typeof AdminLeadershipRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoryRoute: typeof AdminStoryRoute
  AdminVenturesRoute: typeof AdminVenturesRoute
  AdminWorkRoute: typeof AdminWorkRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rayzorverse': {
      id: '/rayzorverse'
      path: '/rayzorverse'
      fullPath: '/rayzorverse'
      preLoaderRoute: typeof RayzorverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/admin/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capabilities': {
      id: '/admin/capabilities'
      path: '/admin/capabilities'
      fullPath: '/admin/capabilities'
      preLoaderRoute: typeof AdminCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaborations': {
      id: '/admin/collaborations'
      path: '/admin/collaborations'
      fullPath: '/admin/collaborations'
      preLoaderRoute: typeof AdminCollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/admin/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leadership': {
      id: '/admin/leadership'
      path: '/admin/leadership'
      fullPath: '/admin/leadership'
      preLoaderRoute: typeof AdminLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/story': {
      id: '/admin/story'
      path: '/admin/story'
      fullPath: '/admin/story'
      preLoaderRoute: typeof AdminStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ventures': {
      id: '/admin/ventures'
      path: '/admin/ventures'
      fullPath: '/admin/ventures'
      preLoaderRoute: typeof AdminVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/work': {
      id: '/admin/work'
      path: '/admin/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AdminWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LibraryRoute: LibraryRoute,
  RayzorverseRoute: RayzorverseRoute,
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminCapabilitiesRoute: AdminCapabilitiesRoute,
  AdminCollaborationsRoute: AdminCollaborationsRoute,
  AdminExperienceRoute: AdminExperienceRoute,
  AdminLeadershipRoute: AdminLeadershipRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoryRoute: AdminStoryRoute,
  AdminVenturesRoute: AdminVenturesRoute,
  AdminWorkRoute: AdminWorkRoute,
  WorkSlugRoute: WorkSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
